<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>1.1.1</Version>
        <Authors>ionut1912</Authors>
        <Company>Shared</Company>
        <PackageId>Shared.Infra</PackageId>
        <Description>Shared infra layer for microservices</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RepositoryUrl>https://github.com/ionut1912/Shared</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.3.12" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.31.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Shared.Domain\Shared.Domain.csproj" />
    </ItemGroup>
</Project>